version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodeapp

  nodeapp:
    image: node:20
    working_dir: /var/www/app/backend/
    volumes:
      - .:/var/www/app/backend
    command: npm start
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
