services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./backend/dist:/usr/src/app/dist
    environment:
      - NODE_ENV=production
      - DB_USER=
      - DB_PASS=
      - DB_HOST=
      - DB_PORT=
      - STORAGE_CONNECTION_STRING=
